
server:
  servlet:
    session:
      cookie:
        name: jinkela_distributed_id


spring:
  application:
    name: jinkela-demo
  flyway:
    baseline-version: 1.0.0
  mvc:
    log-request-details: true
  data:
    web:
      pageable:
        page-parameter: page
        size-parameter: size
  security:
    white-list: "/favicon.ico,/jinkela/open/publickey"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL}/test2?useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}


logging:
  level:
    "org.springframework.security": debug
    "org.springframework.jdbc": debug
    "org.springframework.web": debug
    "org.springframework.transaction": debug
