INSERT INTO testadmin.`_jinkela_menus` (id, created_at, created_by, modified_at, modified_by, active, arguments, component, enabled, hidden, icon, keep_alive, name, parent_id, `path`, permission, sort, title, `type`) VALUES(100, NULL, NULL, NULL, NULL, '', '', '', 1, 0, 'setting', 0, '系统设置', 0, 'permission', '', 44, NULL, 'M');
INSERT INTO testadmin.`_jinkela_menus` (id, created_at, created_by, modified_at, modified_by, active, arguments, component, enabled, hidden, icon, keep_alive, name, parent_id, `path`, permission, sort, title, `type`) VALUES(101, NULL, NULL, NULL, NULL, '', '', 'AdminList', 1, 0, 'User', 1, '管理员', 100, 'admin', 'system:admin:list', 0, NULL, 'C');
INSERT INTO testadmin.`_jinkela_menus` (id, created_at, created_by, modified_at, modified_by, active, arguments, component, enabled, hidden, icon, keep_alive, name, parent_id, `path`, permission, sort, title, `type`) VALUES(102, NULL, NULL, NULL, NULL, '', '', '', 1, 0, '', 0, '管理员详情', 101, '', 'system:admin:detail', 0, NULL, 'A');
INSERT INTO testadmin.`_jinkela_menus` (id, created_at, created_by, modified_at, modified_by, active, arguments, component, enabled, hidden, icon, keep_alive, name, parent_id, `path`, permission, sort, title, `type`) VALUES(103, NULL, NULL, NULL, NULL, '', '', '', 1, 0, '', 0, '管理员新增', 101, '', 'system:admin:add', 0, NULL, 'A');
INSERT INTO testadmin.`_jinkela_menus` (id, created_at, created_by, modified_at, modified_by, active, arguments, component, enabled, hidden, icon, keep_alive, name, parent_id, `path`, permission, sort, title, `type`) VALUES(104, NULL, NULL, NULL, NULL, '', '', '', 1, 0, '', 0, '管理员编辑', 101, '', 'system:admin:edit', 0, NULL, 'A');
INSERT INTO testadmin.`_jinkela_menus` (id, created_at, created_by, modified_at, modified_by, active, arguments, component, enabled, hidden, icon, keep_alive, name, parent_id, `path`, permission, sort, title, `type`) VALUES(105, NULL, NULL, NULL, NULL, '', '', '', 1, 0, '', 0, '管理员删除', 101, '', 'system:admin:del', 0, NULL, 'A');
INSERT INTO testadmin.`_jinkela_menus` (id, created_at, created_by, modified_at, modified_by, active, arguments, component, enabled, hidden, icon, keep_alive, name, parent_id, `path`, permission, sort, title, `type`) VALUES(106, NULL, NULL, NULL, NULL, '', '', '', 1, 0, '', 0, '管理员状态', 101, '', 'system:admin:disable', 0, NULL, 'A');
INSERT INTO testadmin.`_jinkela_menus` (id, created_at, created_by, modified_at, modified_by, active, arguments, component, enabled, hidden, icon, keep_alive, name, parent_id, `path`, permission, sort, title, `type`) VALUES(110, NULL, NULL, NULL, NULL, '', '', 'RoleList', 1, 0, 'Female', 1, '角色管理', 100, 'role', 'system:role:list', 0, NULL, 'C');
INSERT INTO testadmin.`_jinkela_menus` (id, created_at, created_by, modified_at, modified_by, active, arguments, component, enabled, hidden, icon, keep_alive, name, parent_id, `path`, permission, sort, title, `type`) VALUES(111, NULL, NULL, NULL, NULL, '', '', '', 1, 0, '', 0, '角色详情', 110, '', 'system:role:detail', 0, NULL, 'A');
INSERT INTO testadmin.`_jinkela_menus` (id, created_at, created_by, modified_at, modified_by, active, arguments, component, enabled, hidden, icon, keep_alive, name, parent_id, `path`, permission, sort, title, `type`) VALUES(112, NULL, NULL, NULL, NULL, '', '', '', 1, 0, '', 0, '角色新增', 110, '', 'system:role:add', 0, NULL, 'A');
INSERT INTO testadmin.`_jinkela_menus` (id, created_at, created_by, modified_at, modified_by, active, arguments, component, enabled, hidden, icon, keep_alive, name, parent_id, `path`, permission, sort, title, `type`) VALUES(113, NULL, NULL, NULL, NULL, '', '', '', 1, 0, '', 0, '角色编辑', 110, '', 'system:role:edit', 0, NULL, 'A');
INSERT INTO testadmin.`_jinkela_menus` (id, created_at, created_by, modified_at, modified_by, active, arguments, component, enabled, hidden, icon, keep_alive, name, parent_id, `path`, permission, sort, title, `type`) VALUES(114, NULL, NULL, NULL, NULL, '', '', '', 1, 0, '', 0, '角色删除', 110, '', 'system:role:del', 0, NULL, 'A');
INSERT INTO testadmin.`_jinkela_menus` (id, created_at, created_by, modified_at, modified_by, active, arguments, component, enabled, hidden, icon, keep_alive, name, parent_id, `path`, permission, sort, title, `type`) VALUES(120, NULL, NULL, NULL, NULL, '', '', 'MenuList', 1, 0, 'Operation', 1, '菜单管理', 100, 'menu', 'system:menu:list', 0, NULL, 'C');
INSERT INTO testadmin.`_jinkela_menus` (id, created_at, created_by, modified_at, modified_by, active, arguments, component, enabled, hidden, icon, keep_alive, name, parent_id, `path`, permission, sort, title, `type`) VALUES(121, NULL, NULL, NULL, NULL, '', '', '', 1, 0, '', 0, '菜单详情', 120, '', 'system:menu:detail', 0, NULL, 'A');
INSERT INTO testadmin.`_jinkela_menus` (id, created_at, created_by, modified_at, modified_by, active, arguments, component, enabled, hidden, icon, keep_alive, name, parent_id, `path`, permission, sort, title, `type`) VALUES(122, NULL, NULL, NULL, NULL, '', '', '', 1, 0, '', 0, '菜单新增', 120, '', 'system:menu:add', 0, NULL, 'A');
INSERT INTO testadmin.`_jinkela_menus` (id, created_at, created_by, modified_at, modified_by, active, arguments, component, enabled, hidden, icon, keep_alive, name, parent_id, `path`, permission, sort, title, `type`) VALUES(123, NULL, NULL, NULL, NULL, '', '', '', 1, 0, '', 0, '菜单编辑', 120, '', 'system:menu:edit', 0, NULL, 'A');
INSERT INTO testadmin.`_jinkela_menus` (id, created_at, created_by, modified_at, modified_by, active, arguments, component, enabled, hidden, icon, keep_alive, name, parent_id, `path`, permission, sort, title, `type`) VALUES(124, NULL, NULL, NULL, NULL, '', '', '', 1, 0, '', 0, '菜单删除', 120, '', 'system:menu:del', 0, NULL, 'A');
INSERT INTO testadmin.`_jinkela_menus` (id, created_at, created_by, modified_at, modified_by, active, arguments, component, enabled, hidden, icon, keep_alive, name, parent_id, `path`, permission, sort, title, `type`) VALUES(131, NULL, NULL, NULL, NULL, '', '', 'DepartmentList', 1, 0, 'Coordinate', 1, '部门管理', 100, 'department', 'system:dept:list', 0, NULL, 'C');
INSERT INTO testadmin.`_jinkela_menus` (id, created_at, created_by, modified_at, modified_by, active, arguments, component, enabled, hidden, icon, keep_alive, name, parent_id, `path`, permission, sort, title, `type`) VALUES(132, NULL, NULL, NULL, NULL, '', '', '', 1, 0, '', 0, '部门详情', 131, '', 'system:dept:detail', 0, NULL, 'A');
INSERT INTO testadmin.`_jinkela_menus` (id, created_at, created_by, modified_at, modified_by, active, arguments, component, enabled, hidden, icon, keep_alive, name, parent_id, `path`, permission, sort, title, `type`) VALUES(133, NULL, NULL, NULL, NULL, '', '', '', 1, 0, '', 0, '部门新增', 131, '', 'system:dept:add', 0, NULL, 'A');
INSERT INTO testadmin.`_jinkela_menus` (id, created_at, created_by, modified_at, modified_by, active, arguments, component, enabled, hidden, icon, keep_alive, name, parent_id, `path`, permission, sort, title, `type`) VALUES(134, NULL, NULL, NULL, NULL, '', '', '', 1, 0, '', 0, '部门编辑', 131, '', 'system:dept:edit', 0, NULL, 'A');
INSERT INTO testadmin.`_jinkela_menus` (id, created_at, created_by, modified_at, modified_by, active, arguments, component, enabled, hidden, icon, keep_alive, name, parent_id, `path`, permission, sort, title, `type`) VALUES(135, NULL, NULL, NULL, NULL, '', '', '', 1, 0, '', 0, '部门删除', 131, '', 'system:dept:del', 0, NULL, 'A');
INSERT INTO testadmin.`_jinkela_menus` (id, created_at, created_by, modified_at, modified_by, active, arguments, component, enabled, hidden, icon, keep_alive, name, parent_id, `path`, permission, sort, title, `type`) VALUES(140, NULL, NULL, NULL, NULL, '', '', 'PostList', 1, 0, 'PriceTag', 1, '岗位管理', 100, 'post', 'system:post:list', 0, NULL, 'C');
INSERT INTO testadmin.`_jinkela_menus` (id, created_at, created_by, modified_at, modified_by, active, arguments, component, enabled, hidden, icon, keep_alive, name, parent_id, `path`, permission, sort, title, `type`) VALUES(141, NULL, NULL, NULL, NULL, '', '', '', 1, 0, '', 0, '岗位详情', 140, '', 'system:post:detail', 0, NULL, 'A');
INSERT INTO testadmin.`_jinkela_menus` (id, created_at, created_by, modified_at, modified_by, active, arguments, component, enabled, hidden, icon, keep_alive, name, parent_id, `path`, permission, sort, title, `type`) VALUES(142, NULL, NULL, NULL, NULL, '', '', '', 1, 0, '', 0, '岗位新增', 140, '', 'system:post:add', 0, NULL, 'A');
INSERT INTO testadmin.`_jinkela_menus` (id, created_at, created_by, modified_at, modified_by, active, arguments, component, enabled, hidden, icon, keep_alive, name, parent_id, `path`, permission, sort, title, `type`) VALUES(143, NULL, NULL, NULL, NULL, '', '', '', 1, 0, '', 0, '岗位编辑', 140, '', 'system:post:edit', 0, NULL, 'A');
INSERT INTO testadmin.`_jinkela_menus` (id, created_at, created_by, modified_at, modified_by, active, arguments, component, enabled, hidden, icon, keep_alive, name, parent_id, `path`, permission, sort, title, `type`) VALUES(144, NULL, NULL, NULL, NULL, '', '', '', 1, 0, '', 0, '岗位删除', 140, '', 'system:post:del', 0, NULL, 'A');
INSERT INTO testadmin.`_jinkela_menus` (id, created_at, created_by, modified_at, modified_by, active, arguments, component, enabled, hidden, icon, keep_alive, name, parent_id, `path`, permission, sort, title, `type`) VALUES(515, NULL, NULL, NULL, NULL, '', '', 'DictList', 1, 0, 'Box', 0, '字典管理', 100, 'dict', 'setting:dict:``type``:list', 0, NULL, 'C');
INSERT INTO testadmin.`_jinkela_menus` (id, created_at, created_by, modified_at, modified_by, active, arguments, component, enabled, hidden, icon, keep_alive, name, parent_id, `path`, permission, sort, title, `type`) VALUES(516, NULL, NULL, NULL, NULL, '', '', '', 1, 0, '', 0, '字典类型新增', 515, '', 'setting:dict:``type``:add', 0, NULL, 'A');
INSERT INTO testadmin.`_jinkela_menus` (id, created_at, created_by, modified_at, modified_by, active, arguments, component, enabled, hidden, icon, keep_alive, name, parent_id, `path`, permission, sort, title, `type`) VALUES(517, NULL, NULL, NULL, NULL, '', '', '', 1, 0, '', 0, '字典类型编辑', 515, '', 'setting:dict:``type``:edit', 0, NULL, 'A');
INSERT INTO testadmin.`_jinkela_menus` (id, created_at, created_by, modified_at, modified_by, active, arguments, component, enabled, hidden, icon, keep_alive, name, parent_id, `path`, permission, sort, title, `type`) VALUES(518, NULL, NULL, NULL, NULL, '', '', '', 1, 0, '', 0, '字典类型删除', 515, '', 'setting:dict:``type``:del', 0, NULL, 'A');
INSERT INTO testadmin.`_jinkela_menus` (id, created_at, created_by, modified_at, modified_by, active, arguments, component, enabled, hidden, icon, keep_alive, name, parent_id, `path`, permission, sort, title, `type`) VALUES(519, NULL, NULL, NULL, NULL, '/dev_tools/dict', '', 'setting/dict/data/index', 1, 0, '', 0, '字典数据管理', 600, 'dict/data', 'setting:dict:data:list', 0, NULL, 'C');



INSERT INTO testadmin.`_jinkela_role_menu` (id, created_at, created_by, modified_at, modified_by, jinkela_menu_id, jinkela_role_id) VALUES(1, NULL, NULL, NULL, NULL, 100, 1);
INSERT INTO testadmin.`_jinkela_role_menu` (id, created_at, created_by, modified_at, modified_by, jinkela_menu_id, jinkela_role_id) VALUES(2, NULL, NULL, NULL, NULL, 101, 1);
INSERT INTO testadmin.`_jinkela_role_menu` (id, created_at, created_by, modified_at, modified_by, jinkela_menu_id, jinkela_role_id) VALUES(3, NULL, NULL, NULL, NULL, 120, 1);

INSERT INTO testadmin.`_jinkela_roles` (id, created_at, created_by, modified_at, modified_by, enabled, name) VALUES(1, NULL, NULL, NULL, NULL, 1, 'admin');

INSERT INTO testadmin.`_jinkela_user_role` (id, created_at, created_by, modified_at, modified_by, jinkela_role_id, jinkela_user_id) VALUES(1, NULL, NULL, NULL, NULL, 1, 1000000);

INSERT INTO testadmin.`_jinkela_users` (id, created_at, created_by, modified_at, modified_by, account_non_expired, account_non_locked, credentials_non_expired, enabled, password, username, nickname) VALUES(1000000, NULL, NULL, NULL, NULL, 1, 1, 1, 1, '{bcrypt}$2a$10$7n/Oroz9u3cr.mgnBdfjROkJAY5R25T.lOZU2sq1vZGUAj3ZlM66K', 'admin', 'superadmin');